DocumentRoot /var/www/mediawiki

# MFAM-281
ServerName localhost

RewriteEngine On

RewriteCond %{DOCUMENT_ROOT}/.maintenance -f
RewriteRule .* - [R=503]

<IfModule mod_status.c>
    # Allow access to /server-status from localhost
    <If "(%{REMOTE_ADDR} ==  '127.0.0.1' || %{REMOTE_ADDR} == '::1') && %{REQUEST_URI} == '/server-status'">
        RewriteRule ^/?server-status$ - [END]
        SetHandler server-status
    </If>
</IfModule>

# Artificial robots.txt file WIK-1297
RewriteRule ^/?robots\.txt$ /robots.php [NC,L]

# VisualEditor support. T262392
AllowEncodedSlashes NoDecode
RewriteRule ^/?w/rest.php/ - [L]

# Image authorization support
RewriteRule ^/?w/img_auth.php/ - [L]

# Close access to git repo
RedirectMatch 404 /\.git
# Disable directory indexing
Options -Indexes

######## Overwrite log format to include X-Forwarded-For if it is provided ########
RemoteIPHeader ${APACHE_REMOTE_IP_HEADER}
RemoteIPInternalProxy 10.0.0.0/8
RemoteIPInternalProxy 172.16.0.0/12
RemoteIPInternalProxy 192.168.0.0/16
# Cloudflare edge IP ranges (https://www.cloudflare.com/ips-v4, https://www.cloudflare.com/ips-v6)
RemoteIPTrustedProxy 173.245.48.0/20
RemoteIPTrustedProxy 103.21.244.0/22
RemoteIPTrustedProxy 103.22.200.0/22
RemoteIPTrustedProxy 103.31.4.0/22
RemoteIPTrustedProxy 141.101.64.0/18
RemoteIPTrustedProxy 108.162.192.0/18
RemoteIPTrustedProxy 190.93.240.0/20
RemoteIPTrustedProxy 188.114.96.0/20
RemoteIPTrustedProxy 197.234.240.0/22
RemoteIPTrustedProxy 198.41.128.0/17
RemoteIPTrustedProxy 162.158.0.0/15
RemoteIPTrustedProxy 104.16.0.0/13
RemoteIPTrustedProxy 104.24.0.0/14
RemoteIPTrustedProxy 172.64.0.0/13
RemoteIPTrustedProxy 131.0.72.0/22
RemoteIPTrustedProxy 2400:cb00::/32
RemoteIPTrustedProxy 2606:4700::/32
RemoteIPTrustedProxy 2803:f800::/32
RemoteIPTrustedProxy 2405:b500::/32
RemoteIPTrustedProxy 2405:8100::/32
RemoteIPTrustedProxy 2a06:98c0::/29
RemoteIPTrustedProxy 2c0f:f248::/32

LogFormat "%a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" docker

CustomLog "|/usr/bin/rotatelogs -c -f -l -p /rotatelogs-compress.sh -L /var/log/apache2/access_log.current /var/log/apache2/access_log_%Y%m%d 86400" docker
ErrorLog "|/usr/bin/rotatelogs -c -f -l -p /rotatelogs-compress.sh -L /var/log/apache2/error_log.current /var/log/apache2/error_log_%Y%m%d 86400"
